insert into public.destinations (
  external_id,
  name,
  name_zh,
  province,
  province_zh,
  city,
  city_zh,
  latitude,
  longitude,
  scenario,
  distance_km,
  difficulty,
  safety,
  rating,
  has_parking,
  has_toilet,
  min_kid_age,
  image,
  description,
  description_zh,
  updated_at
)
values
  (
    'wuhan-camping-mulan-grassland',
    'Mulan Grassland',
    '木兰草原',
    'Hubei',
    '湖北',
    'Wuhan',
    '武汉黄陂',
    30.9248,
    114.5996,
    'camping',
    0,
    'easy',
    'low_risk',
    4.8,
    true,
    true,
    3,
    'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=1400&q=80',
    'Open grassland, mature scenic facilities, and camping-friendly weekend routes for families.',
    '草原空间开阔，景区配套成熟，适合亲子家庭周末露营、放风筝和轻户外体验。',
    now()
  ),
  (
    'wuhan-camping-jiuzhen-mountain',
    'Jiuzhen Mountain Scenic Area',
    '九真山风景区',
    'Hubei',
    '湖北',
    'Wuhan',
    '武汉蔡甸',
    30.4547,
    114.0186,
    'camping',
    0,
    'easy',
    'low_risk',
    4.6,
    true,
    true,
    4,
    'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1400&q=80',
    'Forest setting near Wuhan with light hiking options and family-friendly outdoor space.',
    '武汉西部森林型景区，可结合轻徒步和营地活动，适合想离城市近一点的家庭。',
    now()
  ),
  (
    'wuhan-creek-mulan-tianchi',
    'Mulan Tianchi',
    '木兰天池',
    'Hubei',
    '湖北',
    'Wuhan',
    '武汉黄陂',
    31.0676,
    114.3119,
    'creek',
    0,
    'moderate',
    'medium_risk',
    4.7,
    true,
    true,
    5,
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80',
    'Mountain water, valley trails, and shaded summer routes suitable for cautious family creek play.',
    '山水峡谷型路线，夏季适合亲水和轻溯溪体验；带孩子需关注天气和水位。',
    now()
  ),
  (
    'wuhan-creek-qingliangzhai',
    'Qingliangzhai Scenic Area',
    '清凉寨',
    'Hubei',
    '湖北',
    'Wuhan',
    '武汉黄陂',
    31.1743,
    114.2672,
    'creek',
    0,
    'moderate',
    'medium_risk',
    4.6,
    true,
    true,
    6,
    'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1400&q=80',
    'Cool mountain valley route with streams and waterfalls, better for school-age children.',
    '山谷、溪流和瀑布资源丰富，清凉感强，更适合学龄儿童家庭结伴出行。',
    now()
  ),
  (
    'wuhan-hiking-maan-forest-park',
    'Ma''anshan Forest Park',
    '马鞍山森林公园',
    'Hubei',
    '湖北',
    'Wuhan',
    '武汉洪山',
    30.5168,
    114.4369,
    'hiking',
    0,
    'easy',
    'low_risk',
    4.6,
    true,
    true,
    3,
    'https://images.unsplash.com/photo-1464822759844-d150ad6d1d88?auto=format&fit=crop&w=1400&q=80',
    'Urban forest park with accessible trails, convenient for first-time family hiking.',
    '城市森林公园，路线选择灵活、到达方便，适合亲子家庭第一次轻徒步。',
    now()
  ),
  (
    'wuhan-hiking-mulan-mountain',
    'Mulan Mountain',
    '木兰山',
    'Hubei',
    '湖北',
    'Wuhan',
    '武汉黄陂',
    31.1139,
    114.3937,
    'hiking',
    0,
    'moderate',
    'medium_risk',
    4.7,
    true,
    true,
    6,
    'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1400&q=80',
    'Classic Wuhan-area mountain route with more climbing, suitable for active families.',
    '武汉周边经典登山路线，爬升感更明显，适合体力较好的亲子家庭。',
    now()
  ),
  (
    'wuhan-picnic-east-lake-greenway',
    'East Lake Greenway',
    '东湖绿道',
    'Hubei',
    '湖北',
    'Wuhan',
    '武汉武昌',
    30.5489,
    114.4091,
    'picnic',
    0,
    'easy',
    'low_risk',
    4.9,
    true,
    true,
    0,
    'https://images.unsplash.com/photo-1521334884684-d80222895322?auto=format&fit=crop&w=1400&q=80',
    'Large lakefront greenway with lawns, cycling paths, toilets, and very family-friendly access.',
    '湖边绿道和草坪资源丰富，公共配套成熟，适合野餐、骑行、遛娃和半日游。',
    now()
  ),
  (
    'wuhan-picnic-fuhe-wetland',
    'Fuhe Wetland',
    '府河湿地',
    'Hubei',
    '湖北',
    'Wuhan',
    '武汉东西湖',
    30.7318,
    114.1637,
    'picnic',
    0,
    'easy',
    'low_risk',
    4.5,
    true,
    false,
    3,
    'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=1400&q=80',
    'Open wetland landscape near the city, good for simple picnic, birdwatching, and sunset walks.',
    '城市近郊湿地空间开阔，适合轻野餐、观鸟和傍晚散步；厕所等配套相对有限。',
    now()
  )
on conflict (external_id) do update
set
  name = excluded.name,
  name_zh = excluded.name_zh,
  province = excluded.province,
  province_zh = excluded.province_zh,
  city = excluded.city,
  city_zh = excluded.city_zh,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  scenario = excluded.scenario,
  distance_km = excluded.distance_km,
  difficulty = excluded.difficulty,
  safety = excluded.safety,
  rating = excluded.rating,
  has_parking = excluded.has_parking,
  has_toilet = excluded.has_toilet,
  min_kid_age = excluded.min_kid_age,
  image = excluded.image,
  description = excluded.description,
  description_zh = excluded.description_zh,
  updated_at = now();
