import type { DestinationItem } from "./types";

export const destinationMockData: DestinationItem[] = [
  {
    id: "wuhan-camping-mulan-grassland",
    name: "Mulan Grassland",
    nameZh: "木兰草原",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉黄陂",
    latitude: 30.9248,
    longitude: 114.5996,
    scenario: "camping",
    distanceKm: 0,
    difficulty: "easy",
    safety: "low_risk",
    rating: 4.8,
    hasParking: true,
    hasToilet: true,
    minKidAge: 3,
    image: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=1400&q=80",
    description: "Open grassland, mature scenic facilities, and camping-friendly weekend routes for families.",
    descriptionZh: "草原空间开阔，景区配套成熟，适合亲子家庭周末露营、放风筝和轻户外体验。"
  },
  {
    id: "wuhan-camping-jiuzhen-mountain",
    name: "Jiuzhen Mountain Scenic Area",
    nameZh: "九真山风景区",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉蔡甸",
    latitude: 30.4547,
    longitude: 114.0186,
    scenario: "camping",
    distanceKm: 0,
    difficulty: "easy",
    safety: "low_risk",
    rating: 4.6,
    hasParking: true,
    hasToilet: true,
    minKidAge: 4,
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1400&q=80",
    description: "Forest setting near Wuhan with light hiking options and family-friendly outdoor space.",
    descriptionZh: "武汉西部森林型景区，可结合轻徒步和营地活动，适合想离城市近一点的家庭。"
  },
  {
    id: "wuhan-creek-mulan-tianchi",
    name: "Mulan Tianchi",
    nameZh: "木兰天池",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉黄陂",
    latitude: 31.0676,
    longitude: 114.3119,
    scenario: "creek",
    distanceKm: 0,
    difficulty: "moderate",
    safety: "medium_risk",
    rating: 4.7,
    hasParking: true,
    hasToilet: true,
    minKidAge: 5,
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80",
    description: "Mountain water, valley trails, and shaded summer routes suitable for cautious family creek play.",
    descriptionZh: "山水峡谷型路线，夏季适合亲水和轻溯溪体验；带孩子需关注天气和水位。"
  },
  {
    id: "wuhan-creek-qingliangzhai",
    name: "Qingliangzhai Scenic Area",
    nameZh: "清凉寨",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉黄陂",
    latitude: 31.1743,
    longitude: 114.2672,
    scenario: "creek",
    distanceKm: 0,
    difficulty: "moderate",
    safety: "medium_risk",
    rating: 4.6,
    hasParking: true,
    hasToilet: true,
    minKidAge: 6,
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1400&q=80",
    description: "Cool mountain valley route with streams and waterfalls, better for school-age children.",
    descriptionZh: "山谷、溪流和瀑布资源丰富，清凉感强，更适合学龄儿童家庭结伴出行。"
  },
  {
    id: "wuhan-hiking-maan-forest-park",
    name: "Ma'anshan Forest Park",
    nameZh: "马鞍山森林公园",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉洪山",
    latitude: 30.5168,
    longitude: 114.4369,
    scenario: "hiking",
    distanceKm: 0,
    difficulty: "easy",
    safety: "low_risk",
    rating: 4.6,
    hasParking: true,
    hasToilet: true,
    minKidAge: 3,
    image: "https://images.unsplash.com/photo-1464822759844-d150ad6d1d88?auto=format&fit=crop&w=1400&q=80",
    description: "Urban forest park with accessible trails, convenient for first-time family hiking.",
    descriptionZh: "城市森林公园，路线选择灵活、到达方便，适合亲子家庭第一次轻徒步。"
  },
  {
    id: "wuhan-hiking-mulan-mountain",
    name: "Mulan Mountain",
    nameZh: "木兰山",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉黄陂",
    latitude: 31.1139,
    longitude: 114.3937,
    scenario: "hiking",
    distanceKm: 0,
    difficulty: "moderate",
    safety: "medium_risk",
    rating: 4.7,
    hasParking: true,
    hasToilet: true,
    minKidAge: 6,
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1400&q=80",
    description: "Classic Wuhan-area mountain route with more climbing, suitable for active families.",
    descriptionZh: "武汉周边经典登山路线，爬升感更明显，适合体力较好的亲子家庭。"
  },
  {
    id: "wuhan-picnic-east-lake-greenway",
    name: "East Lake Greenway",
    nameZh: "东湖绿道",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉武昌",
    latitude: 30.5489,
    longitude: 114.4091,
    scenario: "picnic",
    distanceKm: 0,
    difficulty: "easy",
    safety: "low_risk",
    rating: 4.9,
    hasParking: true,
    hasToilet: true,
    minKidAge: 0,
    image: "https://images.unsplash.com/photo-1521334884684-d80222895322?auto=format&fit=crop&w=1400&q=80",
    description: "Large lakefront greenway with lawns, cycling paths, toilets, and very family-friendly access.",
    descriptionZh: "湖边绿道和草坪资源丰富，公共配套成熟，适合野餐、骑行、遛娃和半日游。"
  },
  {
    id: "wuhan-picnic-fuhe-wetland",
    name: "Fuhe Wetland",
    nameZh: "府河湿地",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉东西湖",
    latitude: 30.7318,
    longitude: 114.1637,
    scenario: "picnic",
    distanceKm: 0,
    difficulty: "easy",
    safety: "low_risk",
    rating: 4.5,
    hasParking: true,
    hasToilet: false,
    minKidAge: 3,
    image: "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=1400&q=80",
    description: "Open wetland landscape near the city, good for simple picnic, birdwatching, and sunset walks.",
    descriptionZh: "城市近郊湿地空间开阔，适合轻野餐、观鸟和傍晚散步；厕所等配套相对有限。"
  }
];
