import type { DestinationItem } from "./types";

export const destinationMockData: DestinationItem[] = [
  {
    id: "wuhan-camping-mulan-grassland",
    name: "Mulan Grassland",
    nameZh: "木兰草原",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉黄陂",
    latitude: 30.9248,
    longitude: 114.5996,
    scenario: "camping",
    distanceKm: 0,
    difficulty: "easy",
    safety: "low_risk",
    rating: 4.8,
    hasParking: true,
    hasToilet: true,
    minKidAge: 3,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/%E6%9C%A8%E5%85%B0%E8%8D%89%E5%8E%9F%E9%A3%8E%E6%99%AF%E5%8C%BA%E5%A4%A7%E9%97%A8_-_panoramio.jpg?width=1400",
    description: "草原空间开阔，景区配套成熟，适合家庭安排轻松的周末露营体验。",
    descriptionZh: "草原空间开阔，景区配套成熟，适合亲子家庭周末露营、放风筝和轻户外体验。"
  },
  {
    id: "wuhan-camping-jiuzhen-mountain",
    name: "九真山风景区",
    nameZh: "九真山风景区",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉蔡甸",
    latitude: 30.4547,
    longitude: 114.0186,
    scenario: "camping",
    distanceKm: 0,
    difficulty: "easy",
    safety: "low_risk",
    rating: 4.6,
    hasParking: true,
    hasToilet: true,
    minKidAge: 4,
    image: "",
    description: "Forest setting near Wuhan with light hiking options and family-friendly outdoor space.",
    descriptionZh: "武汉西部森林型景区，可结合轻徒步和营地活动，适合想离城市近一点的家庭。"
  },
  {
    id: "wuhan-creek-mulan-tianchi",
    name: "Mulan Tianchi",
    nameZh: "木兰天池",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉黄陂",
    latitude: 31.0676,
    longitude: 114.3119,
    scenario: "creek",
    distanceKm: 0,
    difficulty: "moderate",
    safety: "medium_risk",
    rating: 4.7,
    hasParking: true,
    hasToilet: true,
    minKidAge: 5,
    image: "",
    description: "山水峡谷型路线，夏季适合亲水和轻溯溪体验，带孩子需关注天气和水位。",
    descriptionZh: "山水峡谷型路线，夏季适合亲水和轻溯溪体验；带孩子需关注天气和水位。"
  },
  {
    id: "wuhan-creek-qingliangzhai",
    name: "清凉寨",
    nameZh: "清凉寨",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉黄陂",
    latitude: 31.1743,
    longitude: 114.2672,
    scenario: "creek",
    distanceKm: 0,
    difficulty: "moderate",
    safety: "medium_risk",
    rating: 4.6,
    hasParking: true,
    hasToilet: true,
    minKidAge: 6,
    image: "",
    description: "Cool mountain valley route with streams and waterfalls, better for school-age children.",
    descriptionZh: "山谷、溪流和瀑布资源丰富，清凉感强，更适合学龄儿童家庭结伴出行。"
  },
  {
    id: "wuhan-hiking-maan-forest-park",
    name: "Ma'anshan Forest Park",
    nameZh: "马鞍山森林公园",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉洪山",
    latitude: 30.5168,
    longitude: 114.4369,
    scenario: "hiking",
    distanceKm: 0,
    difficulty: "easy",
    safety: "low_risk",
    rating: 4.6,
    hasParking: true,
    hasToilet: true,
    minKidAge: 3,
    image: "",
    description: "Urban forest park with accessible trails, convenient for first-time family hiking.",
    descriptionZh: "城市森林公园，路线选择灵活、到达方便，适合亲子家庭第一次轻徒步。"
  },
  {
    id: "wuhan-hiking-mulan-mountain",
    name: "Mulan Mountain",
    nameZh: "木兰山",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉黄陂",
    latitude: 31.1139,
    longitude: 114.3937,
    scenario: "hiking",
    distanceKm: 0,
    difficulty: "moderate",
    safety: "medium_risk",
    rating: 4.7,
    hasParking: true,
    hasToilet: true,
    minKidAge: 6,
    image: "",
    description: "Classic Wuhan-area mountain route with more climbing, suitable for active families.",
    descriptionZh: "武汉周边经典登山路线，爬升感更明显，适合体力较好的亲子家庭。"
  },
  {
    id: "wuhan-picnic-east-lake-greenway",
    name: "East Lake Greenway",
    nameZh: "东湖绿道",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉武昌",
    latitude: 30.5489,
    longitude: 114.4091,
    scenario: "picnic",
    distanceKm: 0,
    difficulty: "easy",
    safety: "low_risk",
    rating: 4.9,
    hasParking: true,
    hasToilet: true,
    minKidAge: 0,
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Wuhan_East_Lake_01.jpg?width=1400",
    description: "Large lakefront greenway with lawns, cycling paths, toilets, and very family-friendly access.",
    descriptionZh: "湖边绿道和草坪资源丰富，公共配套成熟，适合野餐、骑行、遛娃和半日游。"
  },
  {
    id: "wuhan-picnic-fuhe-wetland",
    name: "Fuhe Wetland",
    nameZh: "府河湿地",
    province: "Hubei",
    provinceZh: "湖北",
    city: "Wuhan",
    cityZh: "武汉东西湖",
    latitude: 30.7318,
    longitude: 114.1637,
    scenario: "picnic",
    distanceKm: 0,
    difficulty: "easy",
    safety: "low_risk",
    rating: 4.5,
    hasParking: true,
    hasToilet: false,
    minKidAge: 3,
    image: "",
    description: "靠近城市的湿地景观开阔，适合简单野餐、观鸟和傍晚散步。",
    descriptionZh: "城市近郊湿地空间开阔，适合轻野餐、观鸟和傍晚散步；厕所等配套相对有限。"
  }
];
