export type Scenario = "camping" | "creek" | "hiking" | "picnic";
export type Difficulty = "easy" | "moderate" | "hard";
export type Safety = "low_risk" | "medium_risk" | "high_risk";

export type DestinationItem = {
  id: string;
  name: string;
  nameZh?: string | null;
  province?: string | null;
  provinceZh?: string | null;
  city: string;
  cityZh?: string | null;
  address?: string | null;
  openingHours?: string | null;
  latitude: number;
  longitude: number;
  scenario: Scenario;
  distanceKm: number;
  difficulty: Difficulty;
  safety: Safety;
  rating: number;
  hasParking: boolean;
  hasToilet: boolean;
  minKidAge: number;
  suitableAgeMin?: number | null;
  suitableAgeMax?: number | null;
  suggestedDuration?: string | null;
  familyBudget?: string | null;
  reservationRequired?: boolean | null;
  parkingDetail?: string | null;
  toiletDetail?: string | null;
  strollerFriendly?: boolean | null;
  petFriendly?: boolean | null;
  bestTime?: string | null;
  image: string;
  description: string;
  descriptionZh?: string | null;
  editorRecommendation?: string | null;
  familyTips?: string | null;
  avoidPitfalls?: string | null;
  isActive?: boolean;
  coverImage?: string | null;
  region?: string | null;
  driveTime?: string | null;
  ticketPrice?: string | null;
  parkingInfo?: string | null;
  toiletInfo?: string | null;
  suitableAge?: string | null;
  tags?: string[] | null;
  reviewCount?: number | null;
  favoriteCount?: number | null;
  viewCount?: number | null;
  shareCount?: number | null;
  badgeText?: string | null;
  featured?: boolean | null;
  homeRecommendation?: {
    recommendation?: string | null;
    customTitle?: string | null;
    customCoverImage?: string | null;
  } | null;
  createdAt?: string | null;
  updatedAt?: string | null;
};

export type DestinationPhoto = {
  id: string;
  destinationId: string;
  imageUrl: string;
  category: "cover" | "gallery" | "play" | "parking" | "toilet" | "food" | "camping" | "water";
  altText?: string | null;
  isCover: boolean;
  sortOrder: number;
  createdAt?: string | null;
  updatedAt?: string | null;
};

export type DestinationFilters = {
  scenario: Scenario | "all";
  maxDistanceKm: number;
  difficulty: Difficulty | "all";
  needParking: boolean;
  needToilet: boolean;
  query?: string;
  city?: string;
};
